// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/calc.proto

package calc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_api_proto_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GameCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // 比如 "move", "skill"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCommand) Reset() {
	*x = GameCommand{}
	mi := &file_api_proto_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand) ProtoMessage() {}

func (x *GameCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand.ProtoReflect.Descriptor instead.
func (*GameCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{1}
}

func (x *GameCommand) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameCommand) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_api_proto_calc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DestroyRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRoomRequest) Reset() {
	*x = DestroyRoomRequest{}
	mi := &file_api_proto_calc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRoomRequest) ProtoMessage() {}

func (x *DestroyRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRoomRequest.ProtoReflect.Descriptor instead.
func (*DestroyRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type DestroyRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRoomResponse) Reset() {
	*x = DestroyRoomResponse{}
	mi := &file_api_proto_calc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRoomResponse) ProtoMessage() {}

func (x *DestroyRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRoomResponse.ProtoReflect.Descriptor instead.
func (*DestroyRoomResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DestroyRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_calc_proto protoreflect.FileDescriptor

const file_api_proto_calc_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/calc.proto\x12\x04calc\",\n" +
	"\x11CreateRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"[\n" +
	"\vGameCommand\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\">\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12DestroyRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"C\n" +
	"\x13DestroyRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc9\x01\n" +
	"\n" +
	"Calculator\x12=\n" +
	"\n" +
	"CreateRoom\x12\x17.calc.CreateRoomRequest\x1a\x14.calc.CommonResponse\"\x00\x128\n" +
	"\vSendCommand\x12\x11.calc.GameCommand\x1a\x14.calc.CommonResponse\"\x00\x12B\n" +
	"\vDestroyRoom\x12\x18.calc.DestroyRoomRequest\x1a\x19.calc.DestroyRoomResponseB\bZ\x06./calcb\x06proto3"

var (
	file_api_proto_calc_proto_rawDescOnce sync.Once
	file_api_proto_calc_proto_rawDescData []byte
)

func file_api_proto_calc_proto_rawDescGZIP() []byte {
	file_api_proto_calc_proto_rawDescOnce.Do(func() {
		file_api_proto_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_calc_proto_rawDesc), len(file_api_proto_calc_proto_rawDesc)))
	})
	return file_api_proto_calc_proto_rawDescData
}

var file_api_proto_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_calc_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),   // 0: calc.CreateRoomRequest
	(*GameCommand)(nil),         // 1: calc.GameCommand
	(*CommonResponse)(nil),      // 2: calc.CommonResponse
	(*DestroyRoomRequest)(nil),  // 3: calc.DestroyRoomRequest
	(*DestroyRoomResponse)(nil), // 4: calc.DestroyRoomResponse
}
var file_api_proto_calc_proto_depIdxs = []int32{
	0, // 0: calc.Calculator.CreateRoom:input_type -> calc.CreateRoomRequest
	1, // 1: calc.Calculator.SendCommand:input_type -> calc.GameCommand
	3, // 2: calc.Calculator.DestroyRoom:input_type -> calc.DestroyRoomRequest
	2, // 3: calc.Calculator.CreateRoom:output_type -> calc.CommonResponse
	2, // 4: calc.Calculator.SendCommand:output_type -> calc.CommonResponse
	4, // 5: calc.Calculator.DestroyRoom:output_type -> calc.DestroyRoomResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_calc_proto_init() }
func file_api_proto_calc_proto_init() {
	if File_api_proto_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_calc_proto_rawDesc), len(file_api_proto_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_calc_proto_goTypes,
		DependencyIndexes: file_api_proto_calc_proto_depIdxs,
		MessageInfos:      file_api_proto_calc_proto_msgTypes,
	}.Build()
	File_api_proto_calc_proto = out.File
	file_api_proto_calc_proto_goTypes = nil
	file_api_proto_calc_proto_depIdxs = nil
}
