// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/calc.proto

package calc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	InitJson      string                 `protobuf:"bytes,2,opt,name=init_json,json=initJson,proto3" json:"init_json,omitempty"` // BattleSession::createFromJson 所需初始化数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_api_proto_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomRequest) GetInitJson() string {
	if x != nil {
		return x.InitJson
	}
	return ""
}

type GameCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // 比如 "move", "skill"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCommand) Reset() {
	*x = GameCommand{}
	mi := &file_api_proto_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand) ProtoMessage() {}

func (x *GameCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand.ProtoReflect.Descriptor instead.
func (*GameCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{1}
}

func (x *GameCommand) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameCommand) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_api_proto_calc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DestroyRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRoomRequest) Reset() {
	*x = DestroyRoomRequest{}
	mi := &file_api_proto_calc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRoomRequest) ProtoMessage() {}

func (x *DestroyRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRoomRequest.ProtoReflect.Descriptor instead.
func (*DestroyRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type DestroyRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRoomResponse) Reset() {
	*x = DestroyRoomResponse{}
	mi := &file_api_proto_calc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRoomResponse) ProtoMessage() {}

func (x *DestroyRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRoomResponse.ProtoReflect.Descriptor instead.
func (*DestroyRoomResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DestroyRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_calc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{5}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ActiveRooms   int32                  `protobuf:"varint,2,opt,name=active_rooms,json=activeRooms,proto3" json:"active_rooms,omitempty"` // 当前正在运行的房间数
	CpuUsage      float32                `protobuf:"fixed32,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`         // 节点的 CPU 占用率
	MemoryUsed    uint64                 `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`    // 已用内存 (MB)
	MaxCapacity   int32                  `protobuf:"varint,5,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"` // 节点最大承载量 (建议值)
	ServerId      string                 `protobuf:"bytes,6,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`           // C++ 实例唯一 ID（用于检测重启）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_calc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HeartbeatResponse) GetActiveRooms() int32 {
	if x != nil {
		return x.ActiveRooms
	}
	return 0
}

func (x *HeartbeatResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatResponse) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *HeartbeatResponse) GetMaxCapacity() int32 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *HeartbeatResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

var File_api_proto_calc_proto protoreflect.FileDescriptor

const file_api_proto_calc_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/calc.proto\x12\x04calc\"I\n" +
	"\x11CreateRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tinit_json\x18\x02 \x01(\tR\binitJson\"[\n" +
	"\vGameCommand\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\">\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12DestroyRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"C\n" +
	"\x13DestroyRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10HeartbeatRequest\"\xc8\x01\n" +
	"\x11HeartbeatResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12!\n" +
	"\factive_rooms\x18\x02 \x01(\x05R\vactiveRooms\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x02R\bcpuUsage\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x04R\n" +
	"memoryUsed\x12!\n" +
	"\fmax_capacity\x18\x05 \x01(\x05R\vmaxCapacity\x12\x1b\n" +
	"\tserver_id\x18\x06 \x01(\tR\bserverId2\x8a\x02\n" +
	"\n" +
	"Calculator\x12=\n" +
	"\n" +
	"CreateRoom\x12\x17.calc.CreateRoomRequest\x1a\x14.calc.CommonResponse\"\x00\x128\n" +
	"\vSendCommand\x12\x11.calc.GameCommand\x1a\x14.calc.CommonResponse\"\x00\x12B\n" +
	"\vDestroyRoom\x12\x18.calc.DestroyRoomRequest\x1a\x19.calc.DestroyRoomResponse\x12?\n" +
	"\fGetHeartbeat\x12\x16.calc.HeartbeatRequest\x1a\x17.calc.HeartbeatResponseB\fZ\n" +
	"./api/calcb\x06proto3"

var (
	file_api_proto_calc_proto_rawDescOnce sync.Once
	file_api_proto_calc_proto_rawDescData []byte
)

func file_api_proto_calc_proto_rawDescGZIP() []byte {
	file_api_proto_calc_proto_rawDescOnce.Do(func() {
		file_api_proto_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_calc_proto_rawDesc), len(file_api_proto_calc_proto_rawDesc)))
	})
	return file_api_proto_calc_proto_rawDescData
}

var file_api_proto_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_calc_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),   // 0: calc.CreateRoomRequest
	(*GameCommand)(nil),         // 1: calc.GameCommand
	(*CommonResponse)(nil),      // 2: calc.CommonResponse
	(*DestroyRoomRequest)(nil),  // 3: calc.DestroyRoomRequest
	(*DestroyRoomResponse)(nil), // 4: calc.DestroyRoomResponse
	(*HeartbeatRequest)(nil),    // 5: calc.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 6: calc.HeartbeatResponse
}
var file_api_proto_calc_proto_depIdxs = []int32{
	0, // 0: calc.Calculator.CreateRoom:input_type -> calc.CreateRoomRequest
	1, // 1: calc.Calculator.SendCommand:input_type -> calc.GameCommand
	3, // 2: calc.Calculator.DestroyRoom:input_type -> calc.DestroyRoomRequest
	5, // 3: calc.Calculator.GetHeartbeat:input_type -> calc.HeartbeatRequest
	2, // 4: calc.Calculator.CreateRoom:output_type -> calc.CommonResponse
	2, // 5: calc.Calculator.SendCommand:output_type -> calc.CommonResponse
	4, // 6: calc.Calculator.DestroyRoom:output_type -> calc.DestroyRoomResponse
	6, // 7: calc.Calculator.GetHeartbeat:output_type -> calc.HeartbeatResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_calc_proto_init() }
func file_api_proto_calc_proto_init() {
	if File_api_proto_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_calc_proto_rawDesc), len(file_api_proto_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_calc_proto_goTypes,
		DependencyIndexes: file_api_proto_calc_proto_depIdxs,
		MessageInfos:      file_api_proto_calc_proto_msgTypes,
	}.Build()
	File_api_proto_calc_proto = out.File
	file_api_proto_calc_proto_goTypes = nil
	file_api_proto_calc_proto_depIdxs = nil
}
